name: Issue Report
description: Report a bug or issue with RapidRAW (not for feature requests)
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and fix the issue.
        
        > **Note:** This template is for reporting bugs and issues only. For feature requests, please use the [Discussions page](../../discussions) instead.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the problem you encountered.
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: Tell us what you thought should happen instead.
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: How can we reproduce this?
      description: List the steps to recreate the issue
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: screenshots-logs
    attributes:
      label: Screenshots or error messages
      description: If you have any screenshots, error messages, or log files, please share them here.
      placeholder: Paste screenshots or error messages here...

  - type: markdown
    attributes:
      value: "### Your Environment"

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - Windows 11
        - Windows 10
        - macOS Apple Silicon
        - macOS Intel
        - Ubuntu 24.04
        - Ubuntu 22.04
        - Other Linux
        - Other (please specify in additional info)
    validations:
      required: true

  - type: input
    id: rapidraw-version
    attributes:
      label: RapidRAW Version
      description: What version of RapidRAW are you using?
      placeholder: e.g., v1.2.3
    validations:
      required: true

  - type: dropdown
    id: ram-amount
    attributes:
      label: Available RAM
      options:
        - 8GB or less
        - 16GB
        - 32GB
        - 64GB or more
    validations:
      required: true

  - type: input
    id: cpu-gpu
    attributes:
      label: CPU / GPU
      description: What CPU and/or GPU (including driver version) are you using? This is helpful for performance / rendering issues.
      placeholder: e.g., Apple M1 Pro, or Intel i7-12700K / NVIDIA RTX 3080

  - type: dropdown
    id: image-storage-type
    attributes:
      label: Image Storage Type
      options:
        - SSD (Internal)
        - HDD (Internal)
        - External SSD
        - External HDD
        - External SD Card
        - External CF express
        - Network storage (NAS)
        - Other

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Any other details that might help us understand the problem?
      placeholder: Any other context, workarounds you've tried, etc...

  - type: checkboxes
    id: similar-issues
    attributes:
      label: Similar issues
      description: Have you checked for similar issues?
      options:
        - label: I have searched existing issues and didn't find a duplicate
          required: true
